### ISSUE TITLE
Alert When Auction has been closed

### ISSUE THREAD

**Issue by WMKCharles** [BobsProgrammingAcademy/ecommerce-auction-website#1]
The only alert that comes is if the auction.creator == user. 
![1](https://user-images.githubusercontent.com/77489500/173245502-9f86fabe-4d93-4542-97c5-5e058319c019.JPG)
But the other two, including auction.buyer == user, don't show.
![2](https://user-images.githubusercontent.com/77489500/173245511-4f9b99a9-93f6-46e7-b5f3-75d2fdd2a2c3.JPG)
You can correct to
![issue](https://user-images.githubusercontent.com/77489500/173245544-1bf7558b-9bb1-48e1-a727-e025866586c1.JPG)
for it to work

**Comment by BobsProgrammingAcademy** [comment]
Thank you for bringing this to our attention. We've added a fix.
